name: pantab tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pre-commit/action@v3.0.0

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12, macos-14]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Build wheels for ${{ matrix.os }}
        uses: pypa/cibuildwheel@v2.16.5
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.14"
          CMAKE_APPLE_SILICON_PROCESSOR: ${{ matrix.os == 'macos-14' && 'arm64' || '' }}
